# Reusable workflow that builds the repository's code, executes tests, and then deploys the packages to NuGet when a push is made to the default branch.

name: CI/CD
 
on:
  push:
    branches:  
      - "master"
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/ci.yml'
  pull_request:
    branches:
      - "master"
  workflow_call:
    inputs:
      release-build:
        required: true
        type: boolean
        default: false
      skip-tests:
        required: false
        type: boolean
        default: false
    secrets:
      REPO_TOKEN:
        required: true
      NUGET_API_KEY:
        required: true

env:
  package-configuration: 'Release'
  
jobs:
  build:
    name: Fetch and Build Source
    runs-on: windows-2022
    outputs:
      BUILD_SUBMODULE_SHA: ${{ steps.submodule-status.outputs.BUILD_SUBMODULE_SHA }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Get Build Submodule Hash
      id: submodule-status
      shell: pwsh
      run: Write-Output "BUILD_SUBMODULE_SHA = $($(-split $(git submodule status build))[0])" >> $ENV:GITHUB_OUTPUT
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2    
    - name: Build
      shell: pwsh      
      run: .\build\Invoke-Build.ps1 -ReleaseBuild:$([System.Convert]::ToBoolean($Env:RELEASE_BUILD)) -PackageConfiguration:$Env:PACKAGE_CONFIGURATION
      env:
        RELEASE_BUILD: ${{ inputs.release-build != '' && inputs.release-build || 'false' }}
        PACKAGE_CONFIGURATION: ${{ env.package-configuration }}
      # Store our compiled assets for subsequent jobs.
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/rel/
    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: artifacts/
  test:
    name: Run Unit Tests
    needs: build
    if: inputs.skip-tests != true
    runs-on: windows-2022
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1.3
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: binaries
        path: bin/rel/
    - name: Execute Test Runner
      shell: pwsh
      run: Get-ChildItem bin\rel\*.Tests.dll | ForEach-Object {vstest.console /Logger:trx`;LogFileName="$($_.BaseName).trx" /ResultsDirectory:testResults $_.FullName}
    - name: Upload Test Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: testResults/
    - name: Generate Report
      if: always()
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      with:
        check_name: Unit Test Results
        files: testResults/**/*.trx
  deploy:
    name: Deploy Packages
    needs: [build, test]
    if: always()
    runs-on: windows-2022
    steps:
    - name: Check Previous Jobs' Results
      if: needs.build.result != 'success' || (needs.test.result != 'success' && inputs.skip-tests != true)
      run: exit 1
    - name: Checkout Build Submodule
      uses: actions/checkout@v4
      with:
        repository: BadEcho/build
        ref: ${{ needs.build.outputs.BUILD_SUBMODULE_SHA }}
        path: build        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Download Package Artifacts
      uses: actions/download-artifact@v4
      with:
        name: packages
        path: artifacts/
    - name: Push to NuGet
      shell: pwsh
      run: .\build\Publish-Packages.ps1 ${{ secrets.NUGET_API_KEY }}
