# Publishes a new release of Bad Echo software to official NuGet feeds.
# To configure this workflow, replace variables with their correct values in the "env" section below.

name: Publish Release

on:
  workflow_dispatch:
    inputs:
      echo-version:
        description: Echo Version
        required: true
jobs:
  publish:
    name: Publish
    runs-on: windows-2022
    env:
      product-Name: Bad Echo Vision
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0      
    - run: git config --global user.email "chamber@badecho.com"
    - run: git config --global user.name "Echo Chamber"
    - name: Create Echo Version
      run: |
        git tag -a ${{ github.event.inputs.echo-version }} HEAD -m "${{ env.product-name }} ${{ github.event.inputs.echo-version }}"
        git push origin ${{ github.event.inputs.echo-version }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Add VSTest to PATH
      uses: darenm/Setup-VSTest@v1.2
    - name: Build
      shell: pwsh
      run: .\build\build.ps1
    - name: Push to NuGet
      env:
        PKG_URL: https://api.nuget.org/v3/index.json
        PKG_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: .\build\push.ps1
      shell: pwsh
    - name: Artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*
